# GruvboxDark
[colors]
foreground = "#ebdbb2"
background = "#282828"

cursor_fg = "#504945"
cursor_bg = "#bdae93"
cursor_border = "#bdae93"

selection_fg = "#ebdbb2"
selection_bg = "#665c54"

ansi = ["#363836","#cc241d","#98971a","#d79921","#458588","#b16286","#689d6a","#d5c4a1"]
brights = ["#928374","#fb4934","#b8bb26","#fabd2f","#83a598","#d3869b","#8ec07c","#a89984"]

[colors.tab_bar]
background = "#32302f"

[colors.tab_bar.active_tab]
fg_color = "#32302f"
bg_color = "#d79921"

[colors.tab_bar.inactive_tab]
fg_color = "#d79921"
bg_color = "#32302f"

[colors.tab_bar.new_tab]
fg_color = "#d79921"
bg_color = "#32302f"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#d79921"
bg_color = "#3c3836"

[colors.tab_bar.new_tab_hover]
fg_color = "#d79921"
bg_color = "#3c3836"
